spring:
  profiles:
    active: dev
  application:
    name: daily-service
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: utf-8
        content-type: text/html
        cache: false
  mvc:
    favicon:
      enabled: false
security:
    user:
       name: admin
       password: 0
server:
  port: 8443
  ssl:
    key-store: .keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcat
mybatis:
  typeAliasesPackage: com.yun.daily.personUser.domain
  mapperLocations: classpath:mappers/**/*.xml
management:
   security:
     enabled: false
     context-path: /admin
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://39.106.13.197:3306/daily?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 39.106.13.197
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 2000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  data:
    mongodb:
      host: 39.106.13.197
      port: 27017
      username: chatdb
      password: chatdbzyjkx
      database: chatDB
      
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://47.105.38.159:3306/daily?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 39.106.13.197
    username: guest
    password: guest
    port: 5672
